#!/usr/bin/env bash
# Idempotent Cloud Agent bootstrap for Qirlpl LIMS.
# Installs workspace + frontend + pdf-service deps, the Playwright Chromium
# runtime used by the local PDF service, and a dev frontend/.env if missing.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

echo "[install] npm install (workspace root)"
npm install

echo "[install] npm install (frontend)"
npm install --prefix frontend

echo "[install] npm install (pdf-service)"
npm install --prefix pdf-service

echo "[install] Playwright Chromium + system deps for the local PDF service"
( cd pdf-service && npx --yes playwright install --with-deps chromium )

ENV_FILE="frontend/.env"
if [ ! -f "$ENV_FILE" ]; then
  echo "[install] Creating $ENV_FILE for local dev"
  cat > "$ENV_FILE" <<EOF
# Local dev config (generated by .cursor/install.sh; frontend/.env is gitignored).
# VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY point at the Railway API gateway.
# Set VITE_SUPABASE_ANON_KEY as a secret for authenticated (login) flows.
VITE_SUPABASE_URL=${VITE_SUPABASE_URL:-https://api-production-284ab.up.railway.app}
VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY:-dev-placeholder-anon-key}
# VITE_PDF_SERVICE_URL intentionally unset: Vite proxies /api/pdf to the local pdf-service.
EOF
else
  echo "[install] $ENV_FILE already exists; leaving it untouched"
fi

echo "[install] done"
