import type { MaintenanceChecklistItem } from './types'

export type MaintenanceCheckpointStatus = 'OK' | 'Not OK'

export type MaintenanceCheckpointRow = {
  key: string
  selected: boolean
  checkPoint: string
  status: MaintenanceCheckpointStatus
  repairIfAny: string
}

export const REPAIR_DEFAULT_OK = 'No Action Required'
export const REPAIR_DEFAULT_NOT_OK = 'Generated by AI'

export function defaultRepairForStatus(status: MaintenanceCheckpointStatus): string {
  return status === 'OK' ? REPAIR_DEFAULT_OK : REPAIR_DEFAULT_NOT_OK
}

function newRowKey(): string {
  return `cp-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`
}

export function checklistItemsToRows(
  items: MaintenanceChecklistItem[] | null | undefined,
): MaintenanceCheckpointRow[] {
  if (!items?.length) return []
  return items.map((item) => ({
    key: newRowKey(),
    selected: true,
    checkPoint: item.checkPoint ?? '',
    status: (item.status === 'Not OK' ? 'Not OK' : 'OK') as MaintenanceCheckpointStatus,
    repairIfAny: item.repairIfAny?.trim() || REPAIR_DEFAULT_OK,
  }))
}

export function rowsToChecklistItems(rows: MaintenanceCheckpointRow[]): MaintenanceChecklistItem[] {
  return rows
    .map((row) => ({
      checkPoint: row.checkPoint.trim(),
      status: row.status,
      repairIfAny: row.repairIfAny.trim(),
    }))
    .filter((row) => row.checkPoint.length > 0)
}

export function parseMaintenanceChecklistFromDb(value: unknown): MaintenanceChecklistItem[] {
  if (!Array.isArray(value)) return []
  const out: MaintenanceChecklistItem[] = []
  for (const item of value) {
    if (!item || typeof item !== 'object') continue
    const row = item as Record<string, unknown>
    const checkPoint = String(row.checkPoint ?? row.checkpoint ?? '').trim()
    if (!checkPoint) continue
    const statusRaw = String(row.status ?? 'OK').trim().toLowerCase()
    const status: MaintenanceChecklistItem['status'] =
      statusRaw === 'not ok' || statusRaw === 'notok' ? 'Not OK' : 'OK'
    out.push({
      checkPoint,
      status,
      repairIfAny: String(row.repairIfAny ?? row.repair_if_any ?? '').trim(),
    })
  }
  return out
}
